export var carsData = [
    { "id": 1, "name": "Acura" },
    { "id": 24, "name": "Alfa Romeo" },
    { "id": 64, "name": "AM General" },
    { "id": 44, "name": "Aston Martin" },
    { "id": 2, "name": "Audi" },
    { "id": 25, "name": "Bentley" },
    { "id": 3, "name": "BMW" },
    { "id": 56, "name": "Bugatti" },
    { "id": 4, "name": "Buick" },
    { "id": 5, "name": "Cadillac" },
    { "id": 6, "name": "Chevrolet" },
    { "id": 26, "name": "Chrysler" },
    { "id": 62, "name": "Daewoo" },
    { "id": 27, "name": "Dodge" },
    { "id": 65, "name": "Eagle" },
    { "id": 46, "name": "Ferrari" },
    { "id": 28, "name": "FIAT" },
    { "id": 50, "name": "Fisker" },
    { "id": 29, "name": "Ford" },
    { "id": 7, "name": "Genesis" },
    { "id": 66, "name": "Geo" },
    { "id": 8, "name": "GMC" },
    { "id": 9, "name": "Honda" },
    { "id": 54, "name": "HUMMER" },
    { "id": 10, "name": "Hyundai" },
    { "id": 11, "name": "INFINITI" },
    { "id": 59, "name": "Isuzu" },
    { "id": 12, "name": "Jaguar" },
    { "id": 30, "name": "Jeep" },
    { "id": 31, "name": "Karma" },
    { "id": 13, "name": "Kia" },
    { "id": 32, "name": "Lamborghini" },
    { "id": 14, "name": "Land Rover" },
    { "id": 33, "name": "Lexus" },
    { "id": 15, "name": "Lincoln" },
    { "id": 45, "name": "Lotus" },
    { "id": 34, "name": "Lucid" },
    { "id": 35, "name": "Maserati" },
    { "id": 51, "name": "Maybach" },
    { "id": 16, "name": "Mazda" },
    { "id": 36, "name": "McLaren" },
    { "id": 37, "name": "Mercedes-Benz" },
    { "id": 53, "name": "Mercury" },
    { "id": 17, "name": "MINI" },
    { "id": 18, "name": "Mitsubishi" },
    { "id": 19, "name": "Nissan" },
    { "id": 61, "name": "Oldsmobile" },
    { "id": 60, "name": "Panoz" },
    { "id": 63, "name": "Plymouth" },
    { "id": 20, "name": "Polestar" },
    { "id": 55, "name": "Pontiac" },
    { "id": 38, "name": "Porsche" },
    { "id": 39, "name": "Ram" },
    { "id": 40, "name": "Rivian" },
    { "id": 41, "name": "Rolls-Royce" },
    { "id": 52, "name": "Saab" },
    { "id": 57, "name": "Saturn" },
    { "id": 48, "name": "Scion" },
    { "id": 47, "name": "smart" },
    { "id": 58, "name": "Spyker" },
    { "id": 21, "name": "Subaru" },
    { "id": 49, "name": "Suzuki" },
    { "id": 42, "name": "Tesla" },
    { "id": 22, "name": "Toyota" },
    { "id": 43, "name": "Volkswagen" },
    { "id": 23, "name": "Volvo" }
]